/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Array: typeof import('./src/components/baInput/components/array.vue')['default']
    BaInput: typeof import('./src/components/baInput/index.vue')['default']
    BaUpload: typeof import('./src/components/baInput/components/baUpload.vue')['default']
    Buttons: typeof import('./src/components/table/fieldRender/buttons.vue')['default']
    ClickCaptcha: typeof import('./src/components/clickCaptcha/index.vue')['default']
    Color: typeof import('./src/components/table/fieldRender/color.vue')['default']
    ComSearch: typeof import('./src/components/table/comSearch/index.vue')['default']
    Contextmenu: typeof import('./src/components/contextmenu/index.vue')['default']
    CreateData: typeof import('./src/components/formItem/createData.vue')['default']
    CustomRender: typeof import('./src/components/table/fieldRender/customRender.vue')['default']
    CustomTemplate: typeof import('./src/components/table/fieldRender/customTemplate.vue')['default']
    Datetime: typeof import('./src/components/table/fieldRender/datetime.vue')['default']
    Default: typeof import('./src/components/mixins/editor/default.vue')['default']
    Editor: typeof import('./src/components/baInput/components/editor.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    FormItem: typeof import('./src/components/formItem/index.vue')['default']
    Header: typeof import('./src/components/table/header/index.vue')['default']
    Icon: typeof import('./src/components/icon/index.vue')['default']
    IconSelector: typeof import('./src/components/baInput/components/iconSelector.vue')['default']
    Image: typeof import('./src/components/table/fieldRender/image.vue')['default']
    Images: typeof import('./src/components/table/fieldRender/images.vue')['default']
    LoginFooter: typeof import('./src/components/mixins/loginFooter.vue')['default']
    RemoteSelect: typeof import('./src/components/baInput/components/remoteSelect.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectFile: typeof import('./src/components/baInput/components/selectFile.vue')['default']
    Svg: typeof import('./src/components/icon/svg/index.vue')['default']
    Switch: typeof import('./src/components/table/fieldRender/switch.vue')['default']
    Table: typeof import('./src/components/table/index.vue')['default']
    Tag: typeof import('./src/components/table/fieldRender/tag.vue')['default']
    Tags: typeof import('./src/components/table/fieldRender/tags.vue')['default']
    Terminal: typeof import('./src/components/terminal/index.vue')['default']
    Url: typeof import('./src/components/table/fieldRender/url.vue')['default']
    UserProfile: typeof import('./src/components/mixins/userProfile.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
